export const EXPENSES_ACTION_TYPES = {
  GET_EXPENSES_START: "expenses/GET_EXPENSES_START",
  GET_EXPENSES_SUCCESS: "expenses/GET_EXPENSES_SUCCESS",
  GET_EXPENSES_FAILED: "expenses/GET_EXPENSES_FAILED",

  GET_EXPENSE_USERS_START: "expenses/GET_EXPENSE_USERS_START",
  GET_EXPENSE_USERS_SUCCESS: "expenses/GET_EXPENSE_USERS_SUCCESS",
  GET_EXPENSE_USERS_FAILED: "expenses/GET_EXPENSE_USERS_FAILED",

  GET_EXPENSE_TYPES_START: "expenses/GET_EXPENSE_TYPES_START",
  GET_EXPENSE_TYPES_SUCCESS: "expenses/GET_EXPENSE_TYPES_SUCCESS",
  GET_EXPENSE_TYPES_FAILED: "expenses/GET_EXPENSE_TYPES_FAILED",

  ADD_EXPENSE_START: "expenses/ADD_EXPENSE_START",
  ADD_EXPENSE_SUCCESS: "expenses/ADD_EXPENSE_SUCCESS",
  ADD_EXPENSE_FAILED: "expenses/ADD_EXPENSE_FAILED",

  VIEW_A_EXPENSE_START: "expenses/VIEW_A_EXPENSE_START",
  VIEW_A_EXPENSE_SUCCESS: "expenses/VIEW_A_EXPENSE_SUCCESS",
  VIEW_A_EXPENSE_FAILED: "expenses/VIEW_A_EXPENSE_FAILED",

  APPROVE_A_EXPENSE_STATUS_START: "expenses/APPROVE_A_EXPENSE_STATUS_START",
  APPROVE_A_EXPENSE_STATUS_SUCCESS: "expenses/APPROVE_A_EXPENSE_STATUS_SUCCESS",
  APPROVE_A_EXPENSE_STATUS_FAILED: "expenses/APPROVE_A_EXPENSE_STATUS_FAILED",

  REIMBURSE_A_EXPENSE_STATUS_START: "expenses/REIMBURSE_A_EXPENSE_STATUS_START",
  REIMBURSE_A_EXPENSE_STATUS_SUCCESS:
    "expenses/REIMBURSE_A_EXPENSE_STATUS_SUCCESS",
  REIMBURSE_A_EXPENSE_STATUS_FAILED:
    "expenses/REIMBURSE_A_EXPENSE_STATUS_FAILED",

  CANCEL_A_EXPENSE_STATUS_START: "expenses/CANCEL_A_EXPENSE_STATUS_START",
  CANCEL_A_EXPENSE_STATUS_SUCCESS: "expenses/CANCEL_A_EXPENSE_STATUS_SUCCESS",
  CANCEL_A_EXPENSE_STATUS_FAILED: "expenses/CANCEL_A_EXPENSE_STATUS_FAILED",
};
