export const PRODUCT_ACTION_TYPES = {
  GET_PRODUCTS_START: "product/GET_PRODUCTS_START",
  GET_PRODUCTS_SUCCESS: "product/GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILED: "product/GET_PRODUCTS_FAILED",

  GET_ALL_PRODUCTS_LIST_START: "product/GET_ALL_PRODUCTS_LIST_START",
  GET_ALL_PRODUCTS_LIST_SUCCESS: "product/GET_ALL_PRODUCTS_LIST_SUCCESS",
  GET_ALL_PRODUCTS_LIST_FAILED: "product/GET_ALL_PRODUCTS_LIST_FAILED",

  GET_PRODUCTS_BRANDLIST_SUCCESS: "product/GET_PRODUCT_BRANDLIST_SUCCESS",
  GET_PRODUCTS_BRANDLIST_FAILED: "product/GET_PRODUCT_BRANDLIST_FAILED",

  GET_PRODUCTS_UNIT_SUCCESS: "product/GET_PRODUCT_UNIT_SUCCESS",
  GET_PRODUCTS_UNIT_FAILED: "product/GET_PRODUCT_UNIT_FAILED",

  GET_PRODUCTS_CATEGORIES_SUCCESS: "product/GET_PRODUCTS_CATEGORIES_SUCCESS",
  GET_PRODUCTS_CATEGORIES_FAILED: "product/GET_PRODUCTS_CATEGORIES_FAILED",

  GET_PRODUCTS_WAREHOUSES_SUCCESS: "product/GET_PRODUCTS_WAREHOUSES_SUCCESS",
  GET_PRODUCTS_WAREHOUSES_FAILED: "product/GET_PRODUCTS_WAREHOUSES_FAILED",

  GET_PRODUCTS_WAREHOUSES_AND_STOCKS_SUCCESS:
    "product/GET_PRODUCTS_WAREHOUSES_AND_STOCKS_SUCCESS",
  GET_PRODUCTS_WAREHOUSES_AND_STOCKS_FAILED:
    "product/GET_PRODUCTS_WAREHOUSES_AND_STOCKS_FAILED",

  GET_PRODUCTS_WAREHOUSE_INFO_SUCCESS:
    "product/GET_PRODUCTS_WAREHOUSE_INFO_SUCCESS",
  GET_PRODUCTS_WAREHOUSE_INFO_FAILED:
    "product/GET_PRODUCTS_WAREHOUSE_INFO_FAILED",

  GET_PRODUCT_BY_ID_START: "product/ GET_PRODUCT_BY_ID_START",
  GET_PRODUCT_BY_ID_SUCCESS: "product/ GET_PRODUCT_BY_ID_STUCCESS",
  GET_PRODUCT_BY_ID_FAILED: "product/ GET_PRODUCT_BY_ID_FAILED",

  GET_PRODUCT_EDIT_HISTORY_SUCCESS: "product/GET_PRODUCT_EDIT_HISTORY_SUCCESS",
  GET_PRODUCT_EDIT_HISTORY_FAILED: "product/GET_PRODUCT_EDIT_HISTORY_FAILED",

  ADD_NEW_PRODUCT_START: "product/ADD_NEW_PRODUCT_START",
  ADD_NEW_PRODUCT_SUCCESS: "product/ADD_NEW_PRODUCT_SUCCESS",
  ADD_NEW_PRODUCT_FAILED: "product/ADD_NEW_PRODUCT_FAILED",

  EDIT_PRODUCT_FEATURE_BY_ID_START: "product/EDIT_PRODUCT_FEATURE_BY_ID_START",
  EDIT_PRODUCT_FEATURE_BY_ID_SUCCESS:
    "product/ EDIT_PRODUCT_FEATURE_BY_ID_SUCCESS",
  EDIT_PRODUCT_FEATURE_BY_ID_FAILED:
    "product/EDIT_PRODUCT_FEATURE_BY_ID_FAILED",

  EDIT_PRODUCT_TRACK_INVENTORY_START: "product/EDIT_TRACK_INVENTORY_START",
  EDIT_PRODUCT_TRACK_INVENTORY_SUCCESS:
    "product/ EDIT_PRODUCT_TRACK_INVENTORY_SUCCESS",
  EDIT_PRODUCT_TRACK_INVENTORY_FAILED:
    "product/EDIT_PRODUCT_TRACK_INVENTORY_FAILED",

  DELETE_PRODUCT_START: "product/DELETE_PRODUCT_START",
  DELETE_PRODUCT_SUCCESS: "product/DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILED: "product/DELETE_PRODUCT_FAILED",
};

// type TProduct = {
//   _id: string;
//   product_name: string;
//   product_image: string;
//   product_code: string;
//   visible: string;
//   brand: string;
//   cost_price: number;
//   in_stock: number;
//   unit: string;
//   reorder_point: number | null;
// };

// export type DispatchActionTypes =
//   | {
//       type: "product/GET_PRODUCTS_START";
//     }
//   | {
//       type: "product/GET_PRODUCTS_SUCCESS";
//       payload: TProduct[];
//     }
//   | {
//       type: "product/GET_PRODUCTS_FAILED";
//       payload: any;
//     };
