export const ORDER_ACTION_TYPES = {
  GET_ORDERS_LIST_START: "orders/GET_ORDERS_LIST_START",
  GET_ORDERS_LIST_SUCCESS: "orders/GET_ORDERS_LIST_SUCCESS",
  GET_ORDERS_LIST_FAILED: "orders/GET_ORDERS_LIST_FAILED",

  GET_ORDER_BY_ID_START: "orders/GET_ORDER_BY_ID_START",
  GET_ORDER_BY_ID_SUCCESS: "orders/GET_ORDER_BY_ID_SUCCESS",
  GET_ORDER_BY_ID_FAILED: "orders/GET_ORDER_BY_ID_FAILED",

  UPDATE_ORDER_STATUS_START: "order/UPDATE_ORDER_STATUS_START",
  UPDATE_ORDER_STATUS_SUCCESS: "order/UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_FAILED: "order/UPDATE_ORDER_STATUS_FAILED",

  GET_INVOICES_LIST_START: "orders/GET_INVOICES_LIST_START",
  GET_INVOICES_LIST_SUCCESS: "orders/GET_INVOICES_LIST_SUCCESS",
  GET_INVOICES_LIST_FAILED: "orders/GET_INVOICES_LIST_FAILED",
};
